//! Minimal example tower plugin.
//!
//! Demonstrates the complete plugin authoring workflow: implement [`Plugin`],
//! annotate the struct with `#[plugin_main]`, annotate tool functions with
//! `#[plugin_export]`, and let the macros generate the four wasm export symbols.
//!
//! This crate is compiled to `wasm32-wasip1` to verify AC1 (compiles to wasm)
//! and AC2 (manifest reports correct fields). It is excluded from
//! `default-members` so it does not appear in a bare `cargo test`.
//!
//! # AC2 verification
//!
//! The `#[cfg(test)]` block below runs on the host target and verifies the
//! manifest fields without requiring a running wasm runtime. The host-side
//! test is sufficient for CI; a full end-to-end test (host loads the .wasm,
//! calls `__plugin_init`, reads the manifest) belongs in spec 11c.
//!
//! # Exported symbols (generated by `#[plugin_main]`)
//!
//! - `__plugin_init() -> *mut u8`
//! - `__plugin_call_tool(ptr: *mut u8, len: usize) -> *mut u8`
//! - `__plugin_on_hook(ptr: *mut u8, len: usize)`
//! - `__plugin_free(ptr: *mut u8, len: usize)`

use plugin_sdk::{
    ABI_VERSION, HookKind, HookPayload, Plugin, PluginManifest, SdkError, ToolDesc, Value,
    plugin_export, plugin_main,
};

// ── Plugin struct ─────────────────────────────────────────────────────────────

/// The hello plugin: exposes a single `greet` tool and one lifecycle hook.
///
/// Apply `#[plugin_main]` to wire up the four wasm export symbols automatically.
#[plugin_main]
pub struct HelloPlugin;

// ── Plugin trait implementation ───────────────────────────────────────────────

impl Plugin for HelloPlugin {
    /// Return the manifest. Called once at load time via `__plugin_init`.
    ///
    /// AC2: manifest must report name="hello", version="0.1.0",
    ///       abi=ABI_VERSION, tools=["greet"], hooks=[BeforeToolCall].
    fn init() -> PluginManifest {
        PluginManifest {
            name: "hello".to_owned(),
            version: "0.1.0".to_owned(),
            abi: ABI_VERSION,
            tools: vec![
                ToolDesc {
                    name: "greet".to_owned(),
                    description: "Return a greeting for the given name.".to_owned(),
                    schema_json: r#"{"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}"#
                        .to_owned(),
                },
                ToolDesc {
                    name: "read_file_echo".to_owned(),
                    description: "Read a workspace-relative file and return its UTF-8 content.".to_owned(),
                    schema_json: r#"{"type":"object","properties":{"path":{"type":"string"}},"required":["path"]}"#
                        .to_owned(),
                },
                ToolDesc {
                    name: "index_put".to_owned(),
                    description: "Persist raw bytes under an opaque key via the AST index capability.".to_owned(),
                    schema_json: r#"{"type":"object","properties":{"key":{"type":"string"},"value":{"type":"string"}},"required":["key","value"]}"#
                        .to_owned(),
                },
                ToolDesc {
                    name: "index_get".to_owned(),
                    description: "Retrieve bytes stored under an opaque key via the AST index capability.".to_owned(),
                    schema_json: r#"{"type":"object","properties":{"key":{"type":"string"}},"required":["key"]}"#
                        .to_owned(),
                },
                ToolDesc {
                    name: "list_files".to_owned(),
                    description: "Return the count and paths of all workspace files known to the host.".to_owned(),
                    schema_json: r#"{"type":"object","properties":{}}"#.to_owned(),
                },
            ],
            hooks: vec![HookKind::BeforeToolCall],
        }
    }

    /// Dispatch a tool call. Delegates to `greet_impl` for the `greet` tool.
    fn call_tool(name: &str, args: Value) -> Result<Value, SdkError> {
        match name {
            "greet" => greet_impl(args),
            "read_file_echo" => read_file_echo_impl(args),
            "index_put" => index_put_impl(args),
            "index_get" => index_get_impl(args),
            "list_files" => list_files_impl(args),
            other => Err(SdkError::ToolNotFound(other.to_owned())),
        }
    }

    /// Handle a lifecycle hook. Logs via the host capability.
    fn on_hook(kind: HookKind, payload: HookPayload) {
        match kind {
            HookKind::BeforeToolCall => {
                if let HookPayload::BeforeToolCall { tool_name, .. } = &payload {
                    plugin_sdk::host::log(&format!("hello: before tool call '{tool_name}'"));
                }
            }
            // AfterToolCall, FileIndexed, FileChanged: no-op for this plugin.
            HookKind::AfterToolCall | HookKind::FileIndexed | HookKind::FileChanged => {}
        }
    }
}

// ── Tool implementations ──────────────────────────────────────────────────────

/// Returns a greeting string for the name extracted from `args`.
///
/// # Arguments
///
/// `args` must be a [`Value::Map`] containing a `"name"` key with a
/// [`Value::Text`] value.
///
/// # Errors
///
/// Returns [`SdkError::InvalidArgs`] if `args` does not contain a `"name"` key
/// or if the value is not a text string.
#[plugin_export]
fn greet_impl(args: Value) -> Result<Value, SdkError> {
    let name = extract_name(&args)?;
    Ok(Value::Text(format!("Hello, {name}!")))
}

/// Reads a workspace-relative file via the host capability and returns the
/// content as a UTF-8 text value.
///
/// # Arguments
///
/// `args` must be a [`Value::Map`] containing a `"path"` key with a
/// [`Value::Text`] workspace-relative path.
///
/// # Errors
///
/// Returns [`SdkError::InvalidArgs`] if `args` is malformed or the path is
/// missing/non-text. Returns [`SdkError::CallFailed`] if the host reports
/// the file was not found or an I/O error occurred, or if the bytes are not
/// valid UTF-8.
#[plugin_export]
fn read_file_echo_impl(args: Value) -> Result<Value, SdkError> {
    let path = extract_text_field(&args, "path")?;
    match plugin_sdk::host::read_file(path) {
        Some(bytes) => {
            let content = String::from_utf8(bytes).map_err(|e| {
                SdkError::CallFailed(format!("file content is not valid UTF-8: {e}"))
            })?;
            Ok(Value::Text(content))
        }
        None => Err(SdkError::CallFailed(format!(
            "host could not read file: {path}"
        ))),
    }
}

/// Persists opaque bytes under an opaque key via the host AST index capability.
///
/// # Arguments
///
/// `args` must be a [`Value::Map`] with:
/// - `"key"`: a [`Value::Text`] opaque key (no `/`, no `..`).
/// - `"value"`: a [`Value::Text`] whose UTF-8 bytes are stored as-is.
///
/// # Errors
///
/// Returns [`SdkError::InvalidArgs`] for malformed args, [`SdkError::CallFailed`]
/// on a host-side error (invalid key or write failure).
#[plugin_export]
fn index_put_impl(args: Value) -> Result<Value, SdkError> {
    let key = extract_text_field(&args, "key")?;
    let value = extract_text_field(&args, "value")?;
    plugin_sdk::host::ast_store_put(key, value.as_bytes()).map_err(SdkError::CallFailed)?;
    Ok(Value::Text("ok".to_owned()))
}

/// Retrieves bytes stored under an opaque key via the host AST index capability.
///
/// # Arguments
///
/// `args` must be a [`Value::Map`] with:
/// - `"key"`: a [`Value::Text`] opaque key.
///
/// # Return value
///
/// Returns [`Value::Text`] with the stored UTF-8 content when the key is present,
/// or [`Value::Null`] when the key is absent.
///
/// # Errors
///
/// Returns [`SdkError::InvalidArgs`] for malformed args, [`SdkError::CallFailed`]
/// if the stored bytes are not valid UTF-8.
#[plugin_export]
fn index_get_impl(args: Value) -> Result<Value, SdkError> {
    let key = extract_text_field(&args, "key")?;
    match plugin_sdk::host::ast_store_get(key) {
        Some(bytes) => {
            let content = String::from_utf8(bytes).map_err(|e| {
                SdkError::CallFailed(format!("stored value is not valid UTF-8: {e}"))
            })?;
            Ok(Value::Text(content))
        }
        None => Ok(Value::Null),
    }
}

/// Calls `host::list_files()` and returns a map with `count` (integer) and
/// `paths` (comma-joined string of workspace-relative paths).
///
/// Demonstrates the Stage 4a `host_list_files` capability end-to-end. The
/// `paths` value is joined with `|` so the result is a single `Value::Text`
/// that is easy to assert in tests without needing structured parsing.
///
/// # Return value
///
/// `Value::Map` with:
/// - `"count"`: `Value::Int(n)` — number of indexed files.
/// - `"paths"`: `Value::Text` — paths joined by `|`, or empty string if none.
#[plugin_export]
fn list_files_impl(_args: Value) -> Result<Value, SdkError> {
    let files = plugin_sdk::host::list_files();
    let count = files.len() as i64;
    let joined = files.join("|");
    Ok(Value::Map(vec![
        ("count".to_owned(), Value::Integer(count)),
        ("paths".to_owned(), Value::Text(joined)),
    ]))
}

fn extract_text_field<'a>(args: &'a Value, field: &str) -> Result<&'a str, SdkError> {
    match args {
        Value::Map(pairs) => {
            for (key, val) in pairs {
                if key == field {
                    return match val {
                        Value::Text(s) => Ok(s.as_str()),
                        _ => Err(SdkError::InvalidArgs(format!(
                            "field '{field}' must be a string"
                        ))),
                    };
                }
            }
            Err(SdkError::InvalidArgs(format!(
                "missing required field '{field}'"
            )))
        }
        _ => Err(SdkError::InvalidArgs(
            "args must be a map object".to_owned(),
        )),
    }
}

fn extract_name(args: &Value) -> Result<&str, SdkError> {
    match args {
        Value::Map(pairs) => {
            for (key, val) in pairs {
                if key == "name" {
                    return match val {
                        Value::Text(s) => Ok(s.as_str()),
                        _ => Err(SdkError::InvalidArgs(
                            "field 'name' must be a string".to_owned(),
                        )),
                    };
                }
            }
            Err(SdkError::InvalidArgs(
                "missing required field 'name'".to_owned(),
            ))
        }
        _ => Err(SdkError::InvalidArgs(
            "args must be a map object".to_owned(),
        )),
    }
}

// ── Host-side tests (AC2) ─────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    /// AC2: manifest reports name/version/abi/tools/hooks correctly.
    #[test]
    fn manifest_fields_are_correct() {
        let manifest = HelloPlugin::init();

        assert_eq!(manifest.name, "hello", "AC2: name");
        assert_eq!(manifest.version, "0.1.0", "AC2: version");
        assert_eq!(manifest.abi, ABI_VERSION, "AC2: abi == ABI_VERSION");
        assert_eq!(manifest.tools.len(), 5, "AC2: five tools");
        assert_eq!(manifest.tools[0].name, "greet", "AC2: greet tool name");
        assert_eq!(
            manifest.tools[1].name, "read_file_echo",
            "AC2: read_file_echo tool name"
        );
        assert_eq!(
            manifest.tools[2].name, "index_put",
            "AC2: index_put tool name"
        );
        assert_eq!(
            manifest.tools[3].name, "index_get",
            "AC2: index_get tool name"
        );
        assert_eq!(
            manifest.tools[4].name, "list_files",
            "AC2: list_files tool name"
        );
        assert_eq!(manifest.hooks, vec![HookKind::BeforeToolCall], "AC2: hooks");
    }

    /// AC1 (host-side): plugin compiles and Plugin trait methods are callable.
    #[test]
    fn greet_tool_returns_greeting() {
        let args = Value::Map(vec![("name".to_owned(), Value::Text("World".to_owned()))]);
        let result = HelloPlugin::call_tool("greet", args).expect("call_tool failed");
        assert_eq!(result, Value::Text("Hello, World!".to_owned()));
    }

    #[test]
    fn unknown_tool_returns_not_found() {
        let result = HelloPlugin::call_tool("unknown", Value::Null);
        assert!(matches!(result, Err(SdkError::ToolNotFound(_))));
    }

    #[test]
    fn greet_with_missing_name_returns_invalid_args() {
        let result = HelloPlugin::call_tool("greet", Value::Map(vec![]));
        assert!(matches!(result, Err(SdkError::InvalidArgs(_))));
    }

    #[test]
    fn greet_with_non_map_args_returns_invalid_args() {
        let result = HelloPlugin::call_tool("greet", Value::Null);
        assert!(matches!(result, Err(SdkError::InvalidArgs(_))));
    }

    /// read_file_echo returns CallFailed when the host stub returns None (non-wasm).
    #[test]
    fn read_file_echo_returns_call_failed_on_non_wasm() {
        // On the host target, host::read_file is a no-op stub returning None.
        let args = Value::Map(vec![("path".to_owned(), Value::Text("any.txt".to_owned()))]);
        let result = HelloPlugin::call_tool("read_file_echo", args);
        assert!(
            matches!(result, Err(SdkError::CallFailed(_))),
            "read_file_echo must return CallFailed when host returns None: {result:?}"
        );
    }

    /// read_file_echo returns InvalidArgs when path field is missing.
    #[test]
    fn read_file_echo_missing_path_returns_invalid_args() {
        let args = Value::Map(vec![]);
        let result = HelloPlugin::call_tool("read_file_echo", args);
        assert!(
            matches!(result, Err(SdkError::InvalidArgs(_))),
            "read_file_echo must return InvalidArgs for missing path: {result:?}"
        );
    }

    /// AC2: manifest serialises to postcard and back correctly.
    #[test]
    fn manifest_round_trips_postcard() {
        let manifest = HelloPlugin::init();
        let encoded = postcard::to_allocvec(&manifest).expect("encode");
        let decoded: PluginManifest = postcard::from_bytes(&encoded).expect("decode");
        assert_eq!(decoded, manifest);
    }
}
