//! Tower Plugin SDK
//!
//! The crate third-party authors depend on to build tower plugins. It provides:
//!
//! - Shared serialisable DTOs: [`PluginManifest`], [`ToolDesc`], [`HookKind`],
//!   [`HookPayload`], [`Value`].
//! - The [`Plugin`] trait a plugin struct must implement.
//! - [`ABI_VERSION`]: the current ABI revision carried in every manifest so the
//!   host (11c) can detect version mismatches without loading plugin logic.
//! - Attribute macros [`plugin_main`] and [`plugin_export`] (re-exported from
//!   the proc-macro crate) that generate the wasm export surface.
//! - [`host`]: the guest-side signatures of the minimal host capabilities a
//!   plugin may call. Nothing else is reachable from guest code.
//!
//! # Compilation targets
//!
//! This crate compiles for both `x86_64-unknown-linux-gnu` (host tests) and
//! `wasm32-wasip1` (the actual plugin binary). It deliberately pulls no
//! host-only dependency (`wasmtime`, `std::fs`, `sled`, etc.).
//!
//! # Serialisation
//!
//! All DTOs use `serde` derive macros. The wire format between the host and a
//! wasm guest is [`postcard`] (binary, no_std+alloc-compatible). The host-side
//! adapter (11c) converts to/from postcard; the MCP adapter (12b) converts to
//! JSON — plugin_sdk never sees JSON.
//!
//! # ABI stability
//!
//! [`ABI_VERSION`] is bumped on any breaking change to the exported function
//! signatures or the serialised DTO layout. Plugins embed the ABI they were
//! compiled against in [`PluginManifest::abi`]; the host (11c) rejects plugins
//! where `manifest.abi != ABI_VERSION`.
//!
//! # Example
//!
//! ```rust
//! use plugin_sdk::{ABI_VERSION, HookKind, HookPayload, Plugin, PluginManifest, SdkError, Value};
//!
//! struct HelloPlugin;
//!
//! impl Plugin for HelloPlugin {
//!     fn init() -> PluginManifest {
//!         PluginManifest {
//!             name: "hello".to_owned(),
//!             version: "0.1.0".to_owned(),
//!             abi: ABI_VERSION,
//!             tools: vec![],
//!             hooks: vec![],
//!         }
//!     }
//!
//!     fn call_tool(name: &str, _args: Value) -> Result<Value, SdkError> {
//!         Err(SdkError::ToolNotFound(name.to_owned()))
//!     }
//!
//!     fn on_hook(_kind: HookKind, _payload: HookPayload) {}
//! }
//!
//! let m = HelloPlugin::init();
//! assert_eq!(m.abi, ABI_VERSION);
//! ```

// Decision: no #![no_std] at the crate level because `std` is available in both
// wasm32-wasip1 (WASI provides std) and the host. Using std keeps the code
// idiomatic. The __private module's alloc usage is compatible with wasm32-wasip1.

pub mod host;
pub mod types;

// Private module: glue called by the macro-generated export functions.
// Not part of the public API — subject to change between ABI versions.
#[doc(hidden)]
pub mod __private;

// Re-export proc macros so consumers write `use plugin_sdk::{plugin_main, plugin_export}`.
pub use plugin_sdk_macros::{plugin_export, plugin_main};

// Flat re-exports for ergonomics.
pub use types::{
    CallRequest, CallResponse, HookEnvelope, HookKind, HookPayload, PluginManifest, SdkError,
    ToolDesc, Value,
};

/// The current ABI version of the plugin SDK.
///
/// This constant is embedded in every [`PluginManifest`] via `manifest.abi`.
/// The host (11c) compares `manifest.abi` against its own `ABI_VERSION` at load
/// time and rejects plugins built against a different ABI revision.
///
/// **Bump this when any of the following change:**
/// - The wasm export function signatures (`__plugin_init`, `__plugin_call_tool`,
///   `__plugin_on_hook`, `__plugin_free`).
/// - The postcard layout of [`PluginManifest`], [`CallRequest`], [`CallResponse`],
///   or [`HookEnvelope`].
///
/// Increment by 1 for each breaking revision. Hosts may choose to support a
/// range of versions (e.g. `ABI_VERSION - 1 ..= ABI_VERSION`) but that policy
/// lives in 11c.
// Decision: bump ABI_VERSION 1 → 2 for spec 11b.
// Why: HookKind::FileIndexed and HookKind::FileChanged are new enum variants;
// adding them changes the postcard discriminant layout for any payload using
// HookKind. Guests built against ABI 1 must be rejected at load time (11c).
// Trade-off: existing plugins built against ABI 1 must be recompiled.
pub const ABI_VERSION: u32 = 2;

/// The guest-side Plugin trait every plugin struct must implement.
///
/// # Object safety
///
/// This trait is NOT object-safe (associated functions, not methods). That is
/// intentional: the host drives the plugin through the four `extern "C"` exports
/// generated by `#[plugin_main]`, not through dynamic dispatch.
pub trait Plugin {
    /// Return the manifest describing this plugin's identity, tools, and hooks.
    ///
    /// Called once at plugin load time via `__plugin_init`. The manifest is
    /// serialised to postcard and returned to the host.
    fn init() -> PluginManifest
    where
        Self: Sized;

    /// Invoke a named tool with the provided arguments.
    ///
    /// # Errors
    ///
    /// Return [`SdkError::ToolNotFound`] if `name` is not a tool this plugin
    /// declared in its manifest. Return [`SdkError::CallFailed`] for execution
    /// errors.
    fn call_tool(name: &str, args: Value) -> Result<Value, SdkError>
    where
        Self: Sized;

    /// React to a lifecycle hook.
    ///
    /// This function is called when the host fires a hook that the plugin
    /// declared in its manifest ([`PluginManifest::hooks`]). Hooks that the
    /// plugin did not subscribe to are never delivered.
    fn on_hook(kind: HookKind, payload: HookPayload)
    where
        Self: Sized;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{HookKind, HookPayload, PluginManifest, SdkError, ToolDesc, Value};

    // ── TDD step 1: manifest round-trips through postcard (RED → GREEN) ───────

    #[test]
    fn manifest_round_trips_postcard() {
        let original = PluginManifest {
            name: "hello".to_owned(),
            version: "0.1.0".to_owned(),
            abi: ABI_VERSION,
            tools: vec![ToolDesc {
                name: "greet".to_owned(),
                description: "Say hello".to_owned(),
                schema_json: "{}".to_owned(),
            }],
            hooks: vec![HookKind::BeforeToolCall],
        };

        let encoded = postcard::to_allocvec(&original).expect("encode");
        let decoded: PluginManifest = postcard::from_bytes(&encoded).expect("decode");

        assert_eq!(decoded.name, original.name);
        assert_eq!(decoded.version, original.version);
        assert_eq!(decoded.abi, ABI_VERSION);
        assert_eq!(decoded.tools.len(), 1);
        assert_eq!(decoded.tools[0].name, "greet");
        assert_eq!(decoded.hooks, vec![HookKind::BeforeToolCall]);
    }

    #[test]
    fn manifest_abi_version_is_embedded() {
        let manifest = PluginManifest {
            name: "test".to_owned(),
            version: "0.0.1".to_owned(),
            abi: ABI_VERSION,
            tools: vec![],
            hooks: vec![],
        };
        assert_eq!(manifest.abi, ABI_VERSION);
    }

    // AC4: two builds with different ABI_VERSION have different manifest.abi.
    // We simulate this by manually constructing manifests with different abi values.
    #[test]
    fn different_abi_versions_are_detectable() {
        let old = PluginManifest {
            name: "plugin".to_owned(),
            version: "1.0.0".to_owned(),
            abi: ABI_VERSION.saturating_sub(1),
            tools: vec![],
            hooks: vec![],
        };
        let current = PluginManifest {
            name: "plugin".to_owned(),
            version: "1.0.0".to_owned(),
            abi: ABI_VERSION,
            tools: vec![],
            hooks: vec![],
        };
        // Host can detect mismatch by comparing manifest.abi to ABI_VERSION.
        assert_ne!(old.abi, current.abi, "mismatched ABI must be detectable");
        assert_eq!(current.abi, ABI_VERSION);
    }

    // ── TDD step 2: hook payload round-trips ─────────────────────────────────

    #[test]
    fn hook_payload_round_trips_postcard() {
        let payload = HookPayload::BeforeToolCall {
            tool_name: "greet".to_owned(),
            args: Value::Text("Alice".to_owned()),
        };
        let envelope = crate::types::HookEnvelope {
            kind: HookKind::BeforeToolCall,
            payload,
        };

        let encoded = postcard::to_allocvec(&envelope).expect("encode");
        let decoded: crate::types::HookEnvelope = postcard::from_bytes(&encoded).expect("decode");

        assert_eq!(decoded.kind, HookKind::BeforeToolCall);
        match decoded.payload {
            HookPayload::BeforeToolCall { tool_name, .. } => {
                assert_eq!(tool_name, "greet");
            }
            _ => panic!("wrong variant"),
        }
    }

    // ── TDD step 3: CallRequest / CallResponse round-trips ───────────────────

    #[test]
    fn call_request_round_trips_postcard() {
        let request = CallRequest {
            tool_name: "greet".to_owned(),
            args: Value::Text("world".to_owned()),
        };

        let encoded = postcard::to_allocvec(&request).expect("encode");
        let decoded: CallRequest = postcard::from_bytes(&encoded).expect("decode");

        assert_eq!(decoded.tool_name, "greet");
        match decoded.args {
            Value::Text(s) => assert_eq!(s, "world"),
            _ => panic!("wrong value variant"),
        }
    }

    #[test]
    fn call_response_ok_round_trips_postcard() {
        let response = CallResponse {
            result: Ok(Value::Text("hello, world".to_owned())),
        };

        let encoded = postcard::to_allocvec(&response).expect("encode");
        let decoded: CallResponse = postcard::from_bytes(&encoded).expect("decode");

        assert!(decoded.result.is_ok());
    }

    #[test]
    fn call_response_err_round_trips_postcard() {
        let response = CallResponse {
            result: Err(SdkError::ToolNotFound("missing".to_owned())),
        };

        let encoded = postcard::to_allocvec(&response).expect("encode");
        let decoded: CallResponse = postcard::from_bytes(&encoded).expect("decode");

        assert!(decoded.result.is_err());
        match decoded.result.unwrap_err() {
            SdkError::ToolNotFound(name) => assert_eq!(name, "missing"),
            _ => panic!("wrong error variant"),
        }
    }

    // ── TDD step 4: Value variants round-trip ─────────────────────────────────

    #[test]
    fn value_variants_round_trip() {
        let cases = vec![
            Value::Null,
            Value::Bool(true),
            Value::Bool(false),
            Value::Integer(42_i64),
            Value::Float(1.5_f64),
            Value::Text("hello".to_owned()),
            Value::Bytes(vec![1, 2, 3]),
            Value::List(vec![Value::Null, Value::Integer(1)]),
            Value::Map(vec![("key".to_owned(), Value::Text("val".to_owned()))]),
        ];

        for value in cases {
            let encoded = postcard::to_allocvec(&value).expect("encode");
            let decoded: Value = postcard::from_bytes(&encoded).expect("decode");
            assert_eq!(decoded, value);
        }
    }

    // ── TDD step 5: __private helpers ────────────────────────────────────────

    #[test]
    fn encode_manifest_produces_length_prefixed_buffer() {
        let manifest = PluginManifest {
            name: "x".to_owned(),
            version: "0".to_owned(),
            abi: ABI_VERSION,
            tools: vec![],
            hooks: vec![],
        };
        let buf = crate::__private::encode_manifest(manifest.clone());

        // First 4 bytes: little-endian u32 payload length.
        assert!(buf.len() >= 4);
        let len = u32::from_le_bytes([buf[0], buf[1], buf[2], buf[3]]) as usize;
        assert_eq!(buf.len(), 4 + len);

        // Payload decodes to the original manifest.
        let decoded: PluginManifest = postcard::from_bytes(&buf[4..]).expect("decode");
        assert_eq!(decoded.name, "x");
    }

    // ── TDD step 6: minimal Plugin impl compiles and works ───────────────────

    struct MinimalPlugin;

    impl Plugin for MinimalPlugin {
        fn init() -> PluginManifest {
            PluginManifest {
                name: "minimal".to_owned(),
                version: "0.1.0".to_owned(),
                abi: ABI_VERSION,
                tools: vec![],
                hooks: vec![],
            }
        }

        fn call_tool(name: &str, _args: Value) -> Result<Value, SdkError> {
            Err(SdkError::ToolNotFound(name.to_owned()))
        }

        fn on_hook(_kind: HookKind, _payload: HookPayload) {}
    }

    #[test]
    fn minimal_plugin_init_returns_correct_manifest() {
        let manifest = MinimalPlugin::init();
        assert_eq!(manifest.name, "minimal");
        assert_eq!(manifest.abi, ABI_VERSION);
        assert!(manifest.tools.is_empty());
        assert!(manifest.hooks.is_empty());
    }

    #[test]
    fn minimal_plugin_call_tool_returns_not_found() {
        let result = MinimalPlugin::call_tool("nonexistent", Value::Null);
        assert!(matches!(result, Err(SdkError::ToolNotFound(_))));
    }
}
